# Generated by Django 5.2.11 on 2026-02-10 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergame',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usergame',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usergame',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='usergame',
            name='status',
            field=models.CharField(choices=[('playing', 'Jugando'), ('completed', 'Completado'), ('backlog', 'Pendiente'), ('dropped', 'Abandonado')], max_length=20),
        ),
    ]
