# Generated by Django 5.2.11 on 2026-02-10 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='followed_by', to='games.profile'),
        ),
    ]
