# Generated by Django 5.2.11 on 2026-02-13 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamelist',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
