# Generated by Django 6.0.2 on 2026-03-18 15:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_game_url_alter_gamelist_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergame',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
