# Generated by Django 6.0.2 on 2026-03-18 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_usergame_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user_game',
            new_name='review',
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(max_length=255),
        ),
    ]
