# Generated by Django 6.0.2 on 2026-03-21 19:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_news_alter_notification_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamelist',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='usergame',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
